server:
  port: 8081

spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql:///my-douyin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 33321480
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 33321480

  data:
    mongodb:
      uri: mongodb://root:33321480@localhost:27017
      database: mydouyin

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 33321480
    virtual-host: mydouyin

#  application:
#    name: mydouyin-nacos # 作为微服务的名称，注册到Nacos时使用
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos服务地址

# 打开监控
management:
  endpoint:
    web:
      exposure:
        include: '*'


# MinIO 配置
minio:
  endpoint: http://localhost:9001      # MinIO服务地址
  fileHost: http://localhost:9001      # 文件地址host
  bucketName: mydouyin                      # 存储桶bucket名称
  accessKey: root                         # 用户名
  secretKey: 33321480                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024
